In [1]:
from QMLE_scipy import *
from explore import *

### 1. Test k=2

In [2]:
# set up initial guess
sigma = 1
lam = 0.5
gamma = 0.1
rho = 0.2
beta = np.array([1,2])
params = [sigma,lam,gamma, rho, *beta]
params

# set up input data
n = 4
T = 4
k = 2
alpha = np.random.normal(0,1,4)
c0 = np.random.normal(0,1,4)
x1 = []
for i in range(T):
    x1.append(np.random.normal(0,1,n*k).reshape(n,k))
y1 = []
for i in range(T+1):
    y1.append(np.random.normal(0,1,4))
# manually setting up a row-normalized spatial weight vector with 0 diagonals for even time points
w0 = np.array([[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,1,0,0]]).reshape(4,4)
w1 = np.array([[0,0,1,0],[1,0,0,0],[0,1,0,0],[1,0,0,0]]).reshape(4,4)
W_ls = []
for i in range(T+1):
    if is_even(i):
        W_ls.append(w0)
    else:
        W_ls.append(w1)

In [3]:
# run optimization with constraints
QMLE_scipy_estimate(x1, y1, W_ls,initial_guess = params,est_coeff = False)

/Users/helangchun/opt/anaconda3/lib/python3.9/site-packages/scipy/optimize/_hessian_update_strategy.py:182: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  warn('delta_grad == 0.0. Check if the approximated '


[sigma,lam,gamma,rho,beta] =  [0.7515664150944951, 0.10541340105305184, 0.20392764564460208, -0.2764516298873153, array([-0.58613801, -0.11630474])]


[0.7515664150944951,
 0.10541340105305184,
 0.20392764564460208,
 -0.2764516298873153,
 array([-0.58613801, -0.11630474])]

In [4]:
QMLE_scipy_estimate(x1, y1, W_ls,initial_guess = params,est_coeff = True)

[sigma,lam,gamma,rho,beta] =  [0.7515664150944951, 0.10541340105305184, 0.20392764564460208, -0.2764516298873153, array([-0.58613801, -0.11630474])]
c0 :  [[ 0.37753275]
 [ 0.27638313]
 [-0.26997775]
 [ 0.15815643]]
alpha :  [[-0.38803911]
 [ 0.07572264]
 [ 0.19046749]
 [ 0.12184898]]
residuals:  [array([[0.12480592],
       [1.30948403],
       [0.5912074 ],
       [0.51248253]]), array([[ 2.17962093],
       [ 0.42444152],
       [ 0.50892604],
       [-0.46328127]]), array([[ 0.13420607],
       [-0.81651658],
       [ 0.17291134],
       [-1.50460198]]), array([[-0.62486475],
       [-0.37249823],
       [-1.24914851],
       [ 0.44114811]])]
asymptotic variance:  [[ 0.11089431 -0.10759708 -0.13669002  0.08855336  0.15135743  0.06727637]
 [-0.10759708  0.25796518  0.23724156 -0.16796034 -0.26711265 -0.11747533]
 [-0.13669002  0.23724156  0.29115615 -0.15682923 -0.25911964 -0.11507433]
 [ 0.08855336 -0.16796034 -0.15682923  0.17242367  0.23605543  0.10342135]
 [ 0.15135743 -0.267112

[[0.7515664150944951,
  0.10541340105305184,
  0.20392764564460208,
  -0.2764516298873153,
  array([-0.58613801, -0.11630474])],
 array([[ 0.37753275],
        [ 0.27638313],
        [-0.26997775],
        [ 0.15815643]]),
 array([[-0.38803911],
        [ 0.07572264],
        [ 0.19046749],
        [ 0.12184898]]),
 [array([[0.12480592],
         [1.30948403],
         [0.5912074 ],
         [0.51248253]]),
  array([[ 2.17962093],
         [ 0.42444152],
         [ 0.50892604],
         [-0.46328127]]),
  array([[ 0.13420607],
         [-0.81651658],
         [ 0.17291134],
         [-1.50460198]]),
  array([[-0.62486475],
         [-0.37249823],
         [-1.24914851],
         [ 0.44114811]])],
 array([[ 0.11089431, -0.10759708, -0.13669002,  0.08855336,  0.15135743,
          0.06727637],
        [-0.10759708,  0.25796518,  0.23724156, -0.16796034, -0.26711265,
         -0.11747533],
        [-0.13669002,  0.23724156,  0.29115615, -0.15682923, -0.25911964,
         -0.11507433],
   

In [5]:
QMLE_scipy_estimate(x1, y1, W_ls,initial_guess = params, est_coeff = False, constrain= False)

/Users/helangchun/Dropbox/QMLE Estimation/QMLE_scipy.py:31: RuntimeWarning: invalid value encountered in log
  obj = -1/2*((n-1)*T)*np.log(2*np.pi)-1/2*((n-1)*T)*np.log(sigma**2)-T*np.log(1-lam)+np.sum(get_S(sigma,lam,gamma, rho, beta))-1/(2*sigma**2)*np.sum(get_V(sigma,lam,gamma, rho, beta))


[sigma,lam,gamma,rho,beta] =  [0.7515651369177437, 0.10540966392599499, 0.20392811616735834, -0.2764503574070688, array([-0.58613675, -0.11630345])]


[0.7515651369177437,
 0.10540966392599499,
 0.20392811616735834,
 -0.2764503574070688,
 array([-0.58613675, -0.11630345])]

In [7]:
QMLE_scipy_estimate(x1, y1, W_ls,initial_guess = params, est_coeff = True, constrain= False)

[sigma,lam,gamma,rho,beta] =  [0.7515651369177437, 0.10540966392599499, 0.20392811616735834, -0.2764503574070688, array([-0.58613675, -0.11630345])]
c0 :  [[ 0.37753034]
 [ 0.27638255]
 [-0.26997762]
 [ 0.15815738]]
alpha :  [[-0.38804046]
 [ 0.0757194 ]
 [ 0.19046917]
 [ 0.12185189]]
residuals:  [array([[0.12481265],
       [1.30948891],
       [0.59121598],
       [0.51248112]]), array([[ 2.1796265 ],
       [ 0.42445113],
       [ 0.50892628],
       [-0.46327671]]), array([[ 0.13420455],
       [-0.81652039],
       [ 0.1729073 ],
       [-1.50460405]]), array([[-0.6248641 ],
       [-0.37249945],
       [-1.2491515 ],
       [ 0.44114273]])]
asymptotic variance:  [[ 0.1108947  -0.10759796 -0.13669074  0.08855404  0.15136021  0.06727753]
 [-0.10759796  0.25796632  0.23724265 -0.16796134 -0.26711714 -0.1174772 ]
 [-0.13669074  0.23724265  0.29115694 -0.15683016 -0.25912375 -0.11507605]
 [ 0.08855404 -0.16796134 -0.15683016  0.17242429  0.23605885  0.10342276]
 [ 0.15136021 -0.267117

[[0.7515651369177437,
  0.10540966392599499,
  0.20392811616735834,
  -0.2764503574070688,
  array([-0.58613675, -0.11630345])],
 array([[ 0.37753034],
        [ 0.27638255],
        [-0.26997762],
        [ 0.15815738]]),
 array([[-0.38804046],
        [ 0.0757194 ],
        [ 0.19046917],
        [ 0.12185189]]),
 [array([[0.12481265],
         [1.30948891],
         [0.59121598],
         [0.51248112]]),
  array([[ 2.1796265 ],
         [ 0.42445113],
         [ 0.50892628],
         [-0.46327671]]),
  array([[ 0.13420455],
         [-0.81652039],
         [ 0.1729073 ],
         [-1.50460405]]),
  array([[-0.6248641 ],
         [-0.37249945],
         [-1.2491515 ],
         [ 0.44114273]])],
 array([[ 0.1108947 , -0.10759796, -0.13669074,  0.08855404,  0.15136021,
          0.06727753],
        [-0.10759796,  0.25796632,  0.23724265, -0.16796134, -0.26711714,
         -0.1174772 ],
        [-0.13669074,  0.23724265,  0.29115694, -0.15683016, -0.25912375,
         -0.11507605],
   

### 2. Test k=1

In [8]:
# set up initial guess
initial_guess = [1.5,0.2,0.5,0.3,1.2] # in the order sigma, lam, gamma, rho, beta (all real numbers)

n = 49
k = 1
T = 10

# generate samples
t_theta = [0.1,0.2,np.array([1]).reshape(k,1),0.5,1] # true parameters
t_gamma, t_rho, t_beta, t_lam, t_sig = t_theta
alpha = np.random.normal(0,1,T).reshape(T,1)
c0 = np.random.normal(0,1,n).reshape(n,1)
l_n = np.ones(n).reshape(n,1)
x = []
for i in range(T):
    x.append(np.random.normal(0,1,n).reshape(n,k))
# manually setting up a row-normalized spatial weight vector with 0 diagonals for even time points
w0 = generate_weight_matrix(n)
w1 = generate_weight_matrix(n)

W_ls = []
for i in range(T+1):
    if is_even(i):
        W_ls.append(w0)
    else:
        W_ls.append(w1)

        V_nt = []
for i in range(T):
    V_nt.append(np.random.normal(0,t_sig,n).reshape(n,1))

Y0 = np.random.normal(0,1,n).reshape(n,1)

y = []
y.append(Y0)
for i in range(T):
    c_vec = t_gamma*y[i]+t_rho*np.matmul(W_ls[i],np.array(y[i]).reshape(n,1))+np.matmul(x[i],np.array(t_beta).reshape(k,1))+c0+alpha[i][0]*l_n+V_nt[i]
    Y_nt = np.matmul(np.linalg.inv(np.identity(n)-t_lam*W_ls[i+1]),c_vec).reshape(n,1)
    y.append(Y_nt)

In [14]:
QMLE_scipy_estimate(x, y, W_ls,initial_guess = initial_guess, constrain= False, est_coeff = False)

[sigma,lam,gamma,rho,beta] =  [0.9016263076788926, 0.47993816752897356, 0.08471182960487085, 0.21332821605780794, array([1.00022781])]


[0.9016263076788926,
 0.47993816752897356,
 0.08471182960487085,
 0.21332821605780794,
 array([1.00022781])]

In [15]:
QMLE_scipy_estimate(x, y, W_ls,initial_guess = initial_guess, constrain= False, est_coeff = True)

ValueError: cannot reshape array of size 10 into shape (49,1)