In [1]:
from QMLE_scipy import *
from explore import *

### 1. Test k=2

In [4]:
# set up initial guess
sigma = 1
lam = 0.5
gamma = 0.1
rho = 0.2
beta = np.array([1,2])
params = [sigma,lam,gamma, rho, *beta]
params

# set up input data
n = 4
T = 4
k = 2
alpha = np.random.normal(0,1,4)
c0 = np.random.normal(0,1,4)
x1 = []
for i in range(T):
    x1.append(np.random.normal(0,1,n*k).reshape(n,k))
y1 = []
for i in range(T+1):
    y1.append(np.random.normal(0,1,4))
# manually setting up a row-normalized spatial weight vector with 0 diagonals for even time points
w0 = np.array([[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,1,0,0]]).reshape(4,4)
w1 = np.array([[0,0,1,0],[1,0,0,0],[0,1,0,0],[1,0,0,0]]).reshape(4,4)
W_ls = []
for i in range(T+1):
    if is_even(i):
        W_ls.append(w0)
    else:
        W_ls.append(w1)

In [5]:
# run optimization with constraints
QMLE_scipy_estimate(x1, y1, W_ls,initial_guess = params,est_coeff = False)

[sigma,lam,gamma,rho,beta] =  [0.5562986375400485, 0.9999999456513948, -0.07208162032924174, 1.1522568096806676, array([0.04571296, 0.33487399])]


[0.5562986375400485,
 0.9999999456513948,
 -0.07208162032924174,
 1.1522568096806676,
 array([0.04571296, 0.33487399])]

In [6]:
QMLE_scipy_estimate(x1, y1, W_ls,initial_guess = params,est_coeff = True)

[sigma,lam,gamma,rho,beta] =  [0.5562986375400485, 0.9999999456513948, -0.07208162032924174, 1.1522568096806676, array([0.04571296, 0.33487399])]
c0 :  [[-0.18627668]
 [-1.00509166]
 [-0.26689707]
 [-0.91207821]]
alpha :  [[ 1.46133067]
 [-1.06023144]
 [ 0.05896894]
 [-0.46006816]]
residuals:  [array([[-0.34078791],
       [-0.80150251],
       [ 0.72220285],
       [ 0.42008757]]), array([[ 0.0848689 ],
       [ 0.83534517],
       [-0.63505606],
       [-0.28515816]]), array([[ 0.47291341],
       [-0.60714595],
       [-0.00204753],
       [ 0.13628009]]), array([[-0.21699438],
       [ 0.57330321],
       [-0.08509932],
       [-0.27120956]])]
asymptotic variance:  [[ 5.07422360e-02 -1.28025371e-02  3.79989300e-03 -1.09875863e-02
   9.93700847e-02  1.68832643e-02]
 [-1.28025384e-02 -4.08683738e-01 -6.90506086e-02 -1.09174799e-01
  -1.28455372e+00 -2.34274303e-01]
 [ 3.79989274e-03 -6.90506078e-02  5.50952532e-02 -1.95227585e-03
  -2.01359466e-01 -3.70360245e-02]
 [-1.09875867e-02 -

[[0.5562986375400485,
  0.9999999456513948,
  -0.07208162032924174,
  1.1522568096806676,
  array([0.04571296, 0.33487399])],
 array([[-0.18627668],
        [-1.00509166],
        [-0.26689707],
        [-0.91207821]]),
 array([[ 1.46133067],
        [-1.06023144],
        [ 0.05896894],
        [-0.46006816]]),
 [array([[-0.34078791],
         [-0.80150251],
         [ 0.72220285],
         [ 0.42008757]]),
  array([[ 0.0848689 ],
         [ 0.83534517],
         [-0.63505606],
         [-0.28515816]]),
  array([[ 0.47291341],
         [-0.60714595],
         [-0.00204753],
         [ 0.13628009]]),
  array([[-0.21699438],
         [ 0.57330321],
         [-0.08509932],
         [-0.27120956]])],
 array([[ 5.07422360e-02, -1.28025371e-02,  3.79989300e-03,
         -1.09875863e-02,  9.93700847e-02,  1.68832643e-02],
        [-1.28025384e-02, -4.08683738e-01, -6.90506086e-02,
         -1.09174799e-01, -1.28455372e+00, -2.34274303e-01],
        [ 3.79989274e-03, -6.90506078e-02,  5.50952

In [7]:
QMLE_scipy_estimate(x1, y1, W_ls,initial_guess = params, est_coeff = False, constrain= False)

[sigma,lam,gamma,rho,beta] =  [0.5824330258837707, 0.9999999982967367, -0.1639870783956191, 0.8113999364967899, array([-0.05099548,  0.24170238])]


[0.5824330258837707,
 0.9999999982967367,
 -0.1639870783956191,
 0.8113999364967899,
 array([-0.05099548,  0.24170238])]

In [8]:
QMLE_scipy_estimate(x1, y1, W_ls,initial_guess = params, est_coeff = True, constrain= False)

[sigma,lam,gamma,rho,beta] =  [0.5824330258837707, 0.9999999982967367, -0.1639870783956191, 0.8113999364967899, array([-0.05099548,  0.24170238])]
c0 :  [[ 0.03934677]
 [-0.80823326]
 [-0.33572081]
 [-0.68385168]]
alpha :  [[ 1.01884983]
 [-0.80801465]
 [ 0.1222088 ]
 [-0.33304398]]
residuals:  [array([[-0.53948065],
       [-0.77568891],
       [ 1.02549883],
       [ 0.28967072]]), array([[ 0.22694145],
       [ 0.72298489],
       [-0.57672947],
       [-0.37319687]]), array([[ 0.57927375],
       [-0.45241383],
       [-0.27719996],
       [ 0.15034004]]), array([[-0.26673455],
       [ 0.50511785],
       [-0.1715694 ],
       [-0.06681389]])]
asymptotic variance:  [[ 5.86731638e-02 -7.15587106e-02 -5.05351138e-03 -2.70746029e-02
  -3.66459533e-03 -3.42255854e-04]
 [-7.15587110e-02  3.08565420e-01  4.33459343e-02  9.29757181e-02
  -4.66084660e-03  1.87285490e-04]
 [-5.05351134e-03  4.33459344e-02  7.90752223e-02  3.14639219e-02
  -6.01727704e-04 -7.07630798e-06]
 [-2.70746029e-02 

[[0.5824330258837707,
  0.9999999982967367,
  -0.1639870783956191,
  0.8113999364967899,
  array([-0.05099548,  0.24170238])],
 array([[ 0.03934677],
        [-0.80823326],
        [-0.33572081],
        [-0.68385168]]),
 array([[ 1.01884983],
        [-0.80801465],
        [ 0.1222088 ],
        [-0.33304398]]),
 [array([[-0.53948065],
         [-0.77568891],
         [ 1.02549883],
         [ 0.28967072]]),
  array([[ 0.22694145],
         [ 0.72298489],
         [-0.57672947],
         [-0.37319687]]),
  array([[ 0.57927375],
         [-0.45241383],
         [-0.27719996],
         [ 0.15034004]]),
  array([[-0.26673455],
         [ 0.50511785],
         [-0.1715694 ],
         [-0.06681389]])],
 array([[ 5.86731638e-02, -7.15587106e-02, -5.05351138e-03,
         -2.70746029e-02, -3.66459533e-03, -3.42255854e-04],
        [-7.15587110e-02,  3.08565420e-01,  4.33459343e-02,
          9.29757181e-02, -4.66084660e-03,  1.87285490e-04],
        [-5.05351134e-03,  4.33459344e-02,  7.9075

### 2. Test k=1

In [12]:
# set up initial guess
initial_guess = [1.5,0.2,0.5,0.3,1.2] # in the order sigma, lam, gamma, rho, beta (all real numbers)

n = 20
k = 1
T = 10

# generate samples
t_theta = [0.1,0.2,np.array([1]).reshape(k,1),0.5,1] # true parameters
t_gamma, t_rho, t_beta, t_lam, t_sig = t_theta
alpha = np.random.normal(0,1,T).reshape(T,1)
c0 = np.random.normal(0,1,n).reshape(n,1)
l_n = np.ones(n).reshape(n,1)
x = []
for i in range(T):
    x.append(np.random.normal(0,1,n).reshape(n,k))
# manually setting up a row-normalized spatial weight vector with 0 diagonals for even time points
w0 = generate_weight_matrix(n)
w1 = generate_weight_matrix(n)

W_ls = []
for i in range(T+1):
    if is_even(i):
        W_ls.append(w0)
    else:
        W_ls.append(w1)

        V_nt = []
for i in range(T):
    V_nt.append(np.random.normal(0,t_sig,n).reshape(n,1))

Y0 = np.random.normal(0,1,n).reshape(n,1)

y = []
y.append(Y0)
for i in range(T):
    c_vec = t_gamma*y[i]+t_rho*np.matmul(W_ls[i],np.array(y[i]).reshape(n,1))+np.matmul(x[i],np.array(t_beta).reshape(k,1))+c0+alpha[i][0]*l_n+V_nt[i]
    Y_nt = np.matmul(np.linalg.inv(np.identity(n)-t_lam*W_ls[i+1]),c_vec).reshape(n,1)
    y.append(Y_nt)

In [13]:
QMLE_scipy_estimate(x, y, W_ls,initial_guess = initial_guess, constrain= False, est_coeff = False)

[sigma,lam,gamma,rho,beta] =  [0.9477842485317376, 0.4843377718481529, 0.09775983433530529, 0.1778393833354655, array([1.01177869])]


[0.9477842485317376,
 0.4843377718481529,
 0.09775983433530529,
 0.1778393833354655,
 array([1.01177869])]

In [14]:
QMLE_scipy_estimate(x, y, W_ls,initial_guess = initial_guess, constrain= False, est_coeff = True)

[sigma,lam,gamma,rho,beta] =  [0.9477842485317376, 0.4843377718481529, 0.09775983433530529, 0.1778393833354655, array([1.01177869])]
c0 :  [[ 0.83718129]
 [ 0.32294156]
 [-0.19215909]
 [-0.01559185]
 [ 0.3095501 ]
 [-0.33983213]
 [ 0.3852128 ]
 [ 0.23396752]
 [-0.52108183]
 [-0.2405159 ]
 [-0.88127035]
 [-0.40184332]
 [ 0.90250388]
 [-0.09404574]
 [ 0.44390636]
 [ 0.26546609]
 [-0.34216856]
 [-0.49621635]
 [-0.11450066]
 [-0.17402486]]
alpha :  [[-0.20628403]
 [ 0.85908252]
 [-0.05209115]
 [-0.93374816]
 [-1.24870385]
 [ 0.47817444]
 [-0.23443742]
 [ 0.86676572]
 [-0.27322709]
 [ 0.74446903]]
residuals:  [array([[-1.05410816],
       [-0.8667966 ],
       [-1.90764425],
       [-1.0386916 ],
       [ 0.94815268],
       [ 0.33281163],
       [-0.3183779 ],
       [-0.31747987],
       [-3.32716732],
       [ 1.38609197],
       [ 0.57543913],
       [-1.37478835],
       [ 0.92523739],
       [-0.71073057],
       [ 0.77105027],
       [-1.11043859],
       [-1.32473805],
       [ 0.80

[[0.9477842485317376,
  0.4843377718481529,
  0.09775983433530529,
  0.1778393833354655,
  array([1.01177869])],
 array([[ 0.83718129],
        [ 0.32294156],
        [-0.19215909],
        [-0.01559185],
        [ 0.3095501 ],
        [-0.33983213],
        [ 0.3852128 ],
        [ 0.23396752],
        [-0.52108183],
        [-0.2405159 ],
        [-0.88127035],
        [-0.40184332],
        [ 0.90250388],
        [-0.09404574],
        [ 0.44390636],
        [ 0.26546609],
        [-0.34216856],
        [-0.49621635],
        [-0.11450066],
        [-0.17402486]]),
 array([[-0.20628403],
        [ 0.85908252],
        [-0.05209115],
        [-0.93374816],
        [-1.24870385],
        [ 0.47817444],
        [-0.23443742],
        [ 0.86676572],
        [-0.27322709],
        [ 0.74446903]]),
 [array([[-1.05410816],
         [-0.8667966 ],
         [-1.90764425],
         [-1.0386916 ],
         [ 0.94815268],
         [ 0.33281163],
         [-0.3183779 ],
         [-0.31747987],
 